import os
os. system("clear")
def banner () :
   print("")
   print("                                                       __")
   print("                              XX")
   print("_________        ______       ~~     _______         ______      ___.    ___.")
   print("XXXXXXXXX.     ,gXXXXXX.      XX    ,XXXXXXXs      ,gXXXXXX.     XXXi    XXX")
   print("XXXXXXXXXX.  ,dXXXXXXXXXs     XX   iXXXXXXXXXi    iXXXXXXXXXX_   XXXb    XXX")
   print("XXX~~~XXXXX  XXXXX~ ~~XXXX.   XX  XXXX~   XXXX   iXXXX~`'~XXXXi  XXXXs   XXX")
   print("XXX    dXXX  XXX       XXXX   XX  XXXXXs_  '~~   XXX`      XXXX  XXXXXb !XXX")
   print("XXX___XXXXX iXXX!       XXX   XX   XXXXXXXXXs   iXXX        XXX  XXX XXi XXX")
   print("XXXXXXXXXX`  XXX.       XXX   XX    ~XXXXXXXXX   XXX        XXX  XXX'XXXx)XX")
   print("XXX          XXXb     gXXX!   XX  XXXX      XXX  XXXb     gXXX   XXX  'XXXXX")
   print("XXX          XXXXXXXXXXXXf    XX  ~XXXXX_gXXXX!  'XXXXXXXXXXXX`  XXX   !XXXX")
   print("XXX           ~XXXXXXXXX`     XX    XXXXXXXXX~    'XXXXXXXXX`    XXX    XXXX")
   print("~~~              ~~X~~`      '~~`     XXXXX~         ~~X~~`      ~~~    '~~~`")
   print("                   ~                  ~~~~~            ~")


b = "\033[0;91m" #RED 
f = "\033[1;92m" #GREEN
c = "\033[1;96m"  #لبني فاتح
l = "\033[1;94m" #موف
v = "\033[0;101m" #تضليل احمر
print(f+"           ●●●●●●●●●●●●●●●")
print(f+"           ●WELCOME TO MY WORLED●")
print(f+"           ●●●●●●●●●●●●●●●")
print("")
print("   ☬☬☬☬☬☬☬☬☬☬☬☬☬☬☬☬☬☬☬☬☬☬☬☬☬☬☬☬☬")
print("")
print(v+"       ♡《《《WELCOME TO MY TOOL》》》♡   ")    
print(b+"THIS TOOL WAS BEEN PROGRAMED bY H⃟I⃟T⃟L⃟E⃟R⃟ H⃟A⃟C⃟K⃟ & MENA MAGDY")
print("MY ACC ON FACEBOOK 》https://www.facebook.com/profile.php?id=100005415136153 ") 
print("")
print("") 
print("My YOUTUBE CHNAL SUBSCRIBE NOW》https://youtu.be/iTaZJtXLeaE")	
	#this code to input user name
kal = input("USER NAME : ")
print("YOUR NAME IS : " +kal)
#print("m3lomat the phone chanal" *100000000)
#name = input ("hit")
v7x = print("nice name....!! ")
password = input("write the password = ")
# if name log in to tool
if password == "hitler hack":
    print("Correct password...$")
    print ("THANK U ....!!")
    
import os
os. system("clear")
b = "\033[0;91m" #RED 
f = "\033[1;92m" #GREEN
#else
#            print("........♤..ERORR..♤...............")    
#            print("WRITE THE CORRECT PASSWORD")
#            print("go to my CHANEL to get corect password")  
#            print("=======》M3LOMAT THE PHONE《======")   
#v = 0
#while v < 10 :
#    print (v)
#    v=v+1
for v in range (10) :
    import time
    time.sleep(1)
    print(b+ "PROSESS")
    print(b+ "Done......■□■□■□■□■□■□■□■□■□■!!")
    print(b+ "WORKED.....................")
import time
print("           ")
time.sleep(1)
print("□□□□□□□□□□0%")
print("Done.......!")
time.sleep(1)
print("■□□□□□□□□20%")
print("Done.......!!")
time.sleep(1)
print("■■□□□□□□□40%")
print("Done.......!!!")
time.sleep(1)
print("■■■□□□□□□60%")
print("Done.......!!!!")
time.sleep(1)
print("■■■■□□□□□80%")
print("Done.......!!!!!")
time.sleep(1)
print("■■■■□□□□□□90%")
print("Done.......!!!!!!")
time.sleep(1)
print("██████████████□99%")
print("Done.......!!!!!!!")
time.sleep(1)
print("■■■■■■■■■■100%")
print("Done.......!!!!!!!!")




import time
time.sleep(1)
print("⋱ ⋮ ⋰   ")
print("⋯ ◯ ⋯ ︵ 　　　　　　^v^")
print("¸︵︵( ░░ )︵.︵.︵          ")
print("(´░░░░░░  ░░░' )      ")
print("`´︶´¯`︶´`︶´︶´`　^v^　　^v^")
print("╔┓┏╦━━╦┓╔┓╔━━╗╔╗")
print("║┗┛║┗━╣┃║┃║╯╰║║║")
print("║┏┓║┏━╣┗╣┗╣╰╯║╠╣")
print("╚┛┗╩━━╩━╩━╩━━╝╚╝")
print("♪♫•*¨*•.¸¸❤¸¸.•*¨*•♫♪")
print("")
import time
time.sleep(1)
print(b+"☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆")
print(f+"《1》TO MAKE FACKE BAGES ☆")
print(b+"☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆")
print("")
print("☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆")
print("《2》INSTALL METASPLOIT☆")
print("☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆")
print("")
print("☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆")
print("《3》TO GET NUMBERS☆")
print("☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆")
print("")
print("☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆")
print("《4》 DDOS ATTACK ☆☆☆")
print("☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆")
print("")
print("☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆")
print("《5》HACK CAMERA WITH HTTPS ☆")
print("☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆")
print("")
print("☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆")
print("《6》INFORMATION GATHERING WITH IP ☆")
print("☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆")
print("")
print("☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆")
print("《7》GET WEBSITE IP FROM DNS☆")
print("☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆")
print("")
print("☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆")
print("《8》WHO PROGRAMED THIS TOOL ☆")
print("☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆")
print("")
print("☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆")
print("《9》 PYTHON L.N.G COLORS☆")
print("☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆")
print("")
print("☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆")
print("《10》 TO REPAIR YOUR TERMUX☆")
print("☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆")
print("")
   
    
    
if hit3 == "1" :    
    print("      Done....■□■□■□■□■□■□■□■□■□■!!")
    print("      SOOON GYS                              ")
    print(" i recomend to you to use copy & paste    ")
   
if hit3 == "2" :
    print("      Done....■□■□■□■□■□■□■□■□■□■!!")
    print("      ┊┊╭━━━╮┊┊╭━━━╮┊┊")
    print("      ┊┊┃┈▋▋┃┊┊┃▋▋┈┃┊┊")
    print("      ┏━╯┈┈┈◣┊┊◢┈┈┈╰━┓")
    print("      ┃┗━╯┈┈┃┊┊┃┈┈╰━┛┃")
    print("      ╰━┳━┳━╯┊┊╰━┳━┳━╯")
    print("      ━━┻━┻━━━━━━┻━┻━━")   
    print(" HELLO FRIEND ....!") 
    print(" WELCOME BACK!!    ")    
    print("     》》》》》☬INSTALL METASPLOIT☬《《《《《   ")
    print("")
    print("")
    print(" ☬☬☬☬☬ ON TERMUX ☬☬☬☬☬                        ")
    print("   《1》OPEN NEW SESSION                     ")
    print("   《2》WRITE [ apt update && apt upgrade ]  ")
    print("   《3》WRITE [ pkg update ]                 ")
    print("   《4》WRITE [ pkg upgrade]                ")
    print("   《5》WRITE [ pkg install unstable-repo ]  ")
    print("   《6》WRITE [ pkg install metasploit ]     ") 
    print("   《7》WRITE [ msfconsole ]   TO RUN        ")
    print("  i recomend to you to use copy & paste       ")    
if hit3 == "3" :
    print("      Done....■□■□■□■□■□■□■□■□■□■!!")
    print("       █████████     ")
    print("       █▄█████▄█    ")
    print("       █▼▼▼▼▼      ")
    print("       █  Destriputed Denil Of Service     ")
    print("       █▲▲▲▲▲     ")
    print("       █████████   ")
    print("       ██ ██  ")
    print("   《1》OPEN NEW SESSION                     ")
    print("   《2》WRITE [ apt update && apt upgrade ]  ")
    print("   《3》WRITE [ pkg update ]                 ")
    print("   《4》WRITE [ pkg upgrade ]                ")
    print("   《5》WRITE [ pkg install python2 ]        ")
    print("   《5》WRITE [ git clone https://github.com/CiKu370/OSIF                ")
    print("   《6》WRITE [  ls ]                                   ")
    print("   《7》WRITE [ cd OSIF ]                               ")
    print("   《8》WRITE [  ls ]                                   ")
    print("   《9》WRITE [ chmod 777 * ]                           ")             
    print("                                                       ")
    print("     i recomend to you to use copy & paste             ")


if hit3 == "4" :
    print("      Done....■□■□■□■□■□■□■□■□■□■!!")
    print(" SOOOON GYSsss ")
    print("  THE MOS USED ")
    print(" ┈┈┈╱▔▔▔▔▔▔╲┈╭━━━╮┈┈")
    print(" ┈┈▕┈╭━╮╭━╮┈▏┃BOO.┃┈┈  ")
    print(" ┈┈▕┈┃╭╯╰╮┃┈▏╰┳━━╯┈┈")
    print(" ┈┈▕┈╰╯╭╮╰╯┈▏┈┃┈┈┈┈┈")
    print(" ┈┈▕┈┈┈┃┃┈┈┈▏━╯┈┈┈┈┈")
    print(" ┈┈▕┈┈┈╰╯┈┈┈▏┈┈┈┈┈┈┈")
    print(" ┈┈▕╱╲╱╲╱╲╱╲▏┈┈┈┈┈┈┈")
    print(" i recomend to you to use copy & paste ")


if hit3 == "6" :
    print("      Done....■□■□■□■□■□■□■□■□■□■!!")
    import socket
    import sys
    from time import *
    from datetime import datetime
####################
####################
#USE==> python3 to run...#
#Coded By MENA MAGDY
#SUBISCRIBE_NOW TO MY CANEL ON U TUBE 
#》》》》》》M3LOMAT THE PHONE《《《《《
####################
####################
    ip=input ("===> ENTER YOUR IP TO START: ")
    t1=datetime.now()
    print("Scanning Start.. %s Please Wait...! "%ip)
    sleep(1)
####################
    try:
        for port in range(1,6553):
            s=socket.socket(socket.AF_INET,socket.SOCK_STREAM)
            if(s.connect_ex((ip,port))==0):
                try:
                    serv=socket.getservbyport(port)

                except socket.error:
                    serv="Unknown Service"
                print ("Port %s Open Service:%s "%(port,serv))
            t2=datetime.now()
        t3=t2-t1
        print ("Scanning Completed On %s"%t3)
    except KeyboardInterrupt:
        print("SEE U SOOON....!")
        print("")
###############################        


if hit3 == "7" :
    print("     Done....■□■□■□■□■□■□■□■□■□■!!")
    import socket
    import sys
    print ("ENTER YOUR TARGET OR DNS : ")
    hostname = input()
    ip=socket.gethostbyname(hostname)
    print ("Host Name Is : ",hostname,    '/n' 'TARGET IP IS : ',ip)  
	     

if hit3 == "5" :
    print("     Done....■□■□■□■□■□■□■□■□■□■!!")
    print("Soooon gyssss                                ")
    print("  i recomend to you to use copy & paste ")





if hit3 == "8" :
    print("     Done....■□■□■□■□■□■□■□■□■□■!!")
    print("                        ")
    import os 
    os. system("clear")
    print("   ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄")
    print("   ████▌▄▌▄▐▐▌█████")
    print("   ████▌▄▌▄▐▐▌▀████")
    print("   ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀")
    print("   ━━━━▣━━◤◢━━▣━━━━━")
    print("   【ツ】    WELCOME  【ツ】      ")
    print("THIS TOOL HAS BEEN PROGRAMED BY MENA MAGDY TO PENTRATION AND ECICAL HACKER")
    print("         MENA MAGDY = H⃟I⃟T⃟L⃟E⃟R⃟ H⃟A⃟C⃟K⃟ ")
    print("MY FACEBOOK ACC ➷➷➷➷➷ = MENA MAGDY ")
    print("  https://www.facebook.com/profile.php?id=100005415136153      ")
    print("MY YOUTUBE CANEL ")
    print("➷➷➷➷➷SUBSCRIBE NOW ➷➷➷➷➷")
    print("M3LOMAT THE PHONE = https://youtu.be/iTaZJtXLeaE    ")
    print("THIS TOOOL HAS BEEN PROGRAMED ONLY PYTHON L.N.G")
    print("MY ACC ON INSTAGRAM ==》 Mena.m.rushdy")
    print("i styding python & java & kotlin & ruby & bash ")
    print("AND SOCIAL ENGINEERING AND I STILL STUDING MOREE")
    print(" VERSTION : 1.2")
    print("╭━ ♥━ ♥━ ♥━ ♥━ ♥━ ♥━ ♥━")
    print("╰╮┏━┳┳┳┓  ┏┳┳┳┳┳┓  ┏┳┳┳┳┳┓")
    print("┏┻╋━╋┻┻┫  ┣┻┻┻┻┻┫  ┣┻┻┻┻┻┫")
    print("┗ⓞ━━━ⓞ┻━┻ⓞ━━ⓞ┻━┻ⓞ━━ⓞ╯")
    print("")
    print("")    
###########################
if hit3 == "9" :
    print("    Done....■□■□■□■□■□■□■□■□■□■!!")
    print(" ╭━ ♥━ ♥━ ♥━ ♥━ ♥━ ♥━ ♥━")
    print(" ╰╮┏━┳┳┳┓  ┏┳┳┳┳┳┓  ┏┳┳┳┳┳┓")
    print(" ┏┻╋━╋┻┻┫  ┣┻┻┻┻┻┫  ┣┻┻┻┻┻┫")
    print(" ┗ⓞ━━━ⓞ┻━┻ⓞ━━ⓞ┻━┻ⓞ━━ⓞ╯")
    print("✿●‿●✿ PYTHON COLORS BT MENA MAGDY ENJOY ✿●‿●✿")
    print(" OPEN THIS FILE COLORS.PY WITH PYTHON")
    print("")
    print(" Regular Colors ")
    print("Black=\[\033[0;30m\]  Black")
    print("Red=\[\033[0;31m\]  Red")
    print("Green=\[\033[0;32m\]  Green")
    print("Yellow=\[\033[0;33m\]  Yellow")
    print("Blue=\[\033[0;34m\]  Blue")
    print("Purple=\[\033[0;35m\]  Purple")
    print("Cyan=\[\033[0;36m\]  Cyan")
    print("White=\[\033[0;37m\]  White")
    print(" Bold ")
    print("BBlack=\[\033[1;30m\]  Black")
    print("BRed=\[\033[1;31m\]  Red")
    print("BGreen=\[\033[1;32m\]  Green")
    print("BYellow=\[\033[1;33m\]  Yellow")
    print("BBlue=\[\033[1;34m\]  Blue")
    print("BPurple=\[\033[1;35m\]  Purple")
    print("BCyan=\[\033[1;36m\]  Cyan")
    print("BWhite=\[\033[1;37m\] White")
    print(" Underline ")
    print("UBlack=\[\033[4;30m\]  Black")
    print("URed=\[\033[4;31m\]  Red")
    print(" Regular Colors ")
    print("Black=\[\033[0;30m\]  Black")
    print("Red=\[\033[0;31m\]  Red")
    print("Green=\[\033[0;32m\]  Green")
    print("Yellow=\[\033[0;33m\]  Yellow")
    print("Blue=\[\033[0;34m\]  Blue")
    print("Purple=\[\033[0;35m\]  Purple")
    print("Cyan=\[\033[0;36m\]  Cyan")
    print("White=\[\033[0;37m\]  White")
    print(" Bold ")
    print("BBlack=\[\033[1;30m\]  Black")
    print("BRed=\[\033[1;31m\]  Red")
    print("BGreen=\[\033[1;32m\]  Green")
    print("BYellow=\[\033[1;33m\]  Yellow")
    print("BBlue=\[\033[1;34m\] Blue")
    print("BPurple=\[\033[1;35m\]  Purple")
    print("BCyan=\[\033[1;36m\]  Cyan")
    print("BWhite=\[\033[1;37m\]  White")
    print(" Underline ")
    print("UBlack=\[\033[4;30m\]  Black")
    print("URed=\[\033[4;31m\] Red")
    print("UGreen=\[\033[4;32m\] Green")
    print("UYellow=\[\033[4;33m\]  Yellow")
    print("UBlue=\[\033[4;34m\]  Blue")
    print("UPurple=\[\033[4;35m\]  Purple")
    print("UCyan=\[\033[4;36m\]  Cyan")
    print("UWhite=\[\033[4;37m\]  White")
    print(" Background ")
    print("On_Black=\[\033[40m\]  Black")
    print("On_Red=\[\033[41m\]  Red")
    print("On_Green=\[\033[42m\]  Green")
    print("On_Yellow=\[\033[43m\]  Yellow")
    print("On_Blue=\[\033[44m\]  Blue")
    print("On_Purple=\[\033[45m\]  Purple")
    print("On_Cyan=\[\033[46m\]  Cyan")
    print("On_White=\[\033[47m\]  White")
    print(" High Intensty ")
    print("IBlack=\[\033[0;90m\]  Black")
    print("IRed=\[\033[0;91m\]  Red")
    print("IGreen=\[\033[0;92m\]  Green")
    print("IYellow=\[\033[0;93m\]  Yellow")
    print("IBlue=\[\033[0;94m\]  Blue")
    print("IPurple=\[\033[0;95m\]  Purple")
    print("ICyan=\[\033[0;96m\]  Cyan")
    print("IWhite=\[\033[0;97m\]  White")
    print(" Bold High Intensty ")
    print("BIBlack=\[\033[1;90m\]  Black")
    print("BIRed=\[\033[1;91m\]  Red")
    print("BIGreen=\[\033[1;92m\]  Green")
    print("BIYellow=\[\033[1;93m\]  Yellow")
    print("BIBlue=\[\033[1;94m\]  Blue")
    print("BIPurple=\[\033[1;95m\]  Purple")
    print("BICyan=\[\033[1;96m\]  Cyan")
    print("BIWhite=\[\033[1;97m\]  White")
    print(" High Intensty backgroundsUGreen=")
    print("	\[\033[4;32m\]  Green")
    print("UYellow=\[\033[4;33m\]  Yellow")
    print("UBlue=\[\033[4;34m\]  Blue")
    print("UPurple=\[\033[4;35m\]  Purple")
    print("UCyan=\[\033[4;36m\]  Cyan")
    print("UWhite=\[\033[4;37m\]  White")
    print(" Background ")
    print("On_Black=\[\033[40m\]  Black")
    print("On_Red=\[\033[41m\]  Red")
    print("On_Green=\[\033[42m\] Green")
    print("On_Yellow=\[\033[43m\] Yellow")
    print("On_Blue=\[\033[44m\]  Blue")
    print("On_Purple=\[\033[45m\]  Purple")
    print("On_Cyan=\[\033[46m\]  Cyan")
    print("On_White=\[\033[47m\]  White")
    print(" High Intensty ")
    print("IBlack=\[\033[0;90m\]  Black")
    print("IRed=\[\033[0;91m\]  Red")
    print("IGreen=\[\033[0;92m\]  Green")
    print("IYellow=\[\033[0;93m\]  Yellow")
    print("IBlue=\[\033[0;94m\]  Blue")
    print("IPurple=\[\033[0;95m\]  Purple")
    print("ICyan=\[\033[0;96m\]  Cyan")
    print("IWhite=\[\033[0;97m\]  White")
    print(" Bold High Intensty ")
    print("BIBlack=\[\033[1;90m\]  Black")
    print("BIRed=\[\033[1;91m\]  Red")
    print("BIGreen=\[\033[1;92m\]  Green")
    print("BIYellow=\[\033[1;93m\]  Yellow")
    print("BIBlue=\[\033[1;94m\]  Blue")
    print("BIPurple=\[\033[1;95m\]  Purple")
    print("BICyan=\[\033[1;96m\]  Cyan")
    print("BIWhite=\[\033[1;97m\]  White")
    print(" High Intensty backgrounds")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    
    	
    	
    	
